---
ID: "ec4a8b12-11bd-4f7d-810f-3b5f17e4b122"
Parent: "5d15ab5d-31af-4f18-94d9-62afad15d6ea"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Sitecore Cognitive Services/Features/Intelligent Media/Person Group/Training Status
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180621T152554Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
